/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
module.exports = {
    gettingStartedSideBar: [
        {
            type: 'doc',
            id: 'introduction'
        },
        {
            type: 'category',
            label: 'Getting Started',
            collapsed: false,
            items: [
                'getting-started/concepts/overview',
                'getting-started/concepts/workflows',
                'getting-started/concepts/resiliency',
            ],
        },
        {
            type: 'category',
            label: 'Building with Conductor',
            collapsed: false,
            items: [
                'conductor/workflow',
                {
                    type: 'category',
                    label: 'Operators',
                    collapsed: true,
                    items: [
                        'conductor/operators/decision',
                        'conductor/operators/while',
                        'conductor/operators/forkjoin'
                    ]
                },
                {
                    type: 'category',
                    label: 'Built-in Tasks',
                    collapsed: true,
                    items: [
                        'conductor/system-tasks/http',
                        'conductor/system-tasks/jq_transform',
                        'conductor/system-tasks/business_rule'
                    ]
                },
                'conductor/kitchensink'
            ],
        },
    ],
    apiSidebar: [
        {
            type: 'autogenerated',
            dirName: 'api'
        }
    ],
    sdkSidebar: [
        {
            type: 'autogenerated',
            dirName: 'sdk'
        },
    ],
    aclSidebar: [
        {
            type: 'autogenerated',
            dirName: 'acl'
        },
    ],
    schedulerSidebar: [
        {
            type: 'autogenerated',
            dirName: 'scheduler'
        },
        {
            type: 'autogenerated',
            dirName: 'events'
        },
        {
            type: 'autogenerated',
            dirName: 'metrics'
        },
        {
            type: 'autogenerated',
            dirName: 'testing'
        },
        {
            type: 'autogenerated',
            dirName: 'performance'
        },
        {
            type: 'autogenerated',
            dirName: 'cicd'
        },
    ],
    codelabSidebar: [
        {
            type: 'category',
            label: 'Code Lab',
            collapsed: false,
            link: {type: 'doc', id: 'codelab/index'},
            items: [
                'codelab/setup',
            ],
        }
    ],
};
