/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
module.exports = {
    gettingStartedSideBar: [
        {
            type: 'doc',
            id: 'introduction'
        },
        {
            type: 'category',
            label: 'Getting Started',
            collapsed: false,
            items: [
                'getting-started/concepts/overview',
                'getting-started/concepts/workflows',
                'getting-started/concepts/resiliency',
                'getting-started/concepts/orchestration',
            ],
        },
        {
            type: 'category',
            label: 'Building with Conductor',
            collapsed: false,
            items: [
                {
                    type: 'doc',
                    id: 'conductor/workflow',
                },
                {
                    type: 'category',
                    label: 'Configuration',
                    collapsed: true,
                    collapsible: true,
                    items: [
                        {
                        type: 'autogenerated',
                        dirName: 'conductor/configuration',
                        },
                    ]
                },
                {
                    type: 'category',
                    label: 'Operators',
                    collapsed: true,
                    collapsible: true,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'conductor/operators',
                        }
                    ]
                },
                {
                    type: 'category',
                    label: 'Conductor Tasks',
                    collapsed: true,
                    collapsible: true,
                    items: [
                        {
                        type: 'autogenerated',
                        dirName: 'conductor/system-tasks',
                        },
                    ]
                },
                {
                    type: 'doc',
                    id: 'conductor/kitchensink',
                },
                {
                    type: 'doc',
                    id: 'conductor/execute',
                },
            ],
        },
    ],
    apiSidebar: [
        {
            type: 'category',
            label: 'Conductor APIs',
            collapsed: true,
            collapsible: true,
            items: [
                {
                type: 'autogenerated',
                dirName: 'api',
                },
            ]
        },
        {
            type: 'category',
            label: 'Conductor SDKs',
            collapsed: true,
            collapsible: true,
            items: [
                {
                type: 'autogenerated',
                dirName: 'sdk',
                },
            ]
        },
    ],
    aclSidebar: [
        {
            type: 'autogenerated',
            dirName: 'acl'
        },
    ],
    schedulerSidebar: [
        {
            type: 'autogenerated',
            dirName: 'scheduler'
        },
        {
            type: 'autogenerated',
            dirName: 'events'
        },
        {
            type: 'autogenerated',
            dirName: 'metrics'
        },
        {
            type: 'autogenerated',
            dirName: 'testing'
        },
        {
            type: 'autogenerated',
            dirName: 'performance'
        },
        {
            type: 'autogenerated',
            dirName: 'cicd'
        },
    ],
    codelabSidebar: [
        {
            type: 'category',
            label: 'Code Lab',
            collapsed: false,
            link: {type: 'doc', id: 'codelab/index'},
            items: [
                'codelab/setup',
            ],
        }
    ],
};
