name: Check pull requests

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install dependencies
        run: yarn
      - name: Check format code
        run: yarn prettier:check
      - name: Check build code
        run: yarn build
