# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Staging Deployment

on:
  workflow_dispatch:
  push:
    branches: [staging]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - run: npm install
      - run: npm run build
      #          https://github.com/orkes-io/orkesio-site.git
      #         "https://$USER_NAME:$API_TOKEN_GITHUB@$GITHUB_SERVER/$DESTINATION_REPOSITORY_USERNAME/$DESTINATION_REPOSITORY_NAME.git"
      - run: ls -larth
      - run: |
          CLONE_DIR=$(mktemp -d)
          echo $CLONE_DIR
          git config --global user.email "${{ secrets.GH_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GH_USER }}"
          git config -l
          git clone --single-branch --branch "main" "https://${{secrets.GH_USER}}:${{secrets.GH_DEPLOY_TOKEN}}@github.com/orkes-io/orkesio-site-staging.git" "$CLONE_DIR"
          ls -la "$CLONE_DIR"
          rm -rf $CLONE_DIR/content/*
          rsync -a ./build/ $CLONE_DIR/content/
          echo "Moving to clone directory: $CLONE_DIR"
          cd $CLONE_DIR
          echo "Running Git Status"
          gitstatustext=`git status -s`
          echo "Git Status: $gitstatustext"
          echo "Running Git Push If Needed"
          [ ! "$gitstatustext" == "" ]  && (git add . && git commit -m "Adding website changes ${{ github.run_id }}-${{ github.run_number }}" && git push) || echo "Nothing to push"
